version: '3.3'

volumes:
  media_value:
  static_value:
  postgres_data:

services:

  frontend:
    image: lukart80/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend

  backend:
    image: lukart80/foodgram_backend
    volumes:
      - media_value:/code/media/
      - static_value:/code/static/
    depends_on:
      - db

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
