# Generated by Django 3.2.9 on 2021-12-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_units',
            new_name='measurement_unit',
        ),
    ]
