# Generated by Django 3.2.9 on 2021-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_measure_units_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(max_length=7, verbose_name='Код цвета')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
